this commit will add the getTopics feature and compled the 3rd ticket
ColemDev/projects.nc.be.nc-news pull request #2
Opened 2022-08-02 14:19 UTC by ColemDev

2022-08-02 14:24 UTC, scar1377 requested changes
Hi Michael. The code looks good, just need a sad path test

2022-08-02 14:24 UTC, scar1377 commented on controllers/nc_news.controller.js
> +      console.log(topics, "controller topics");
remove console.logs

2022-08-02 14:24 UTC, scar1377 commented on __tests__/app.test.js
> +  });
Need a sad path - 404 path not found  e.g. /api/topiccccc

2022-08-03 10:04 UTC, ColemDev commented on controllers/nc_news.controller.js
> +      console.log(topics, "controller topics");
Okay this is resolved now. Would I normally send a new pull request or would we just resolve this one?

2022-08-03 10:04 UTC, ColemDev commented on __tests__/app.test.js
> +  });
A sad path has been added and the code pushed.

2022-08-03 11:30 UTC, scar1377 approved these changes
All good to merge!

2022-08-03 11:55 UTC, merged